

defaults:
  - base_config
  - override network: a21
  - override data: synthetic
  - _self_

data:
  downsample: 1
  version: 1

mode:
    no_summary_images: True

run:
    distributed: False

network:
    classification:
        active: False
    vertex:
        active: False
