

defaults:
  - base_config
  - override network: a21
  - override data: synthetic
  - _self_

data:
  downsample: 1
  version: 1

mode:
    no_summary_images: True

run:
    distributed: False
    run_length: 500
    run_units: iteration
    compute_mode: XPU

network:
  depth: 6
