
defaults:
  - base_config
  - override framework: torch
  - _self_
  
data:
  downsample: 1 # Change to 0
  version: 2
  data_format: channels_first
  paths:
    active: 
      - train
      - val

network:
  n_initial_filters: 64
  classification:
    active: False
    detach: True
  vertex:
    active: False
    detach: True
  blocks_deepest_layer: 3
  blocks_final: 3
  depth: 6 # changed from 5 to 6
  upsampling: convolutional
run:
  id: ds(0)_filters(32)_train_2023-02-28-fp32
  minibatch_size: 1
  run_length: 25000
  run_units: iteration
  precision: float32
  distributed: False
  compute_mode: CUDA
  # profile: True
output_dir: "//lus/grand/projects/datascience/cadams/CT-SN-RUNS"
