defaults:
  - base_config
  - override framework: torch
  - _self_
data:
  downsample: 1
  version: 2


network:
  n_initial_filters: 64
  classification:
    active: True
    detach: True
  vertex:
    active: True
    detach: True
  blocks_deepest_layer: 3
  blocks_final: 3
  depth: 5
run:
  iterations: 20000
  precision: float32
  epoch: 1000
output_dir: "output/${framework.name}/${network.name}/${run.id}/ds${data.downsample}"
