defaults:
  - base_config
  - override framework: torch
  - _self_
data:
  downsample: 0
  version: 2
  paths:
    active:
      - train
      - val

network:
  n_initial_filters: 24
  classification:
    active: True
    detach: True
  vertex:
    active: True
    detach: True
  blocks_deepest_layer: 3
  blocks_final: 2
  depth: 7
  normalization: group
  # upsampling: convolutional
run:
  run_length: 20000
  run_units: iteration
  precision: float32
  # epoch: 1000
output_dir: "output/"
