defaults:
  - base_config
  - override framework: torch
  - _self_
data:
  downsample: 1
  version: 2
  paths:
    active:
      - train
      - val


network:
  n_initial_filters: 32
  classification:
    active: False
  vertex:
    active: False
  blocks_deepest_layer: 3
  blocks_final: 3
  depth: 6
  # upsampling: convolutional
run:
  run_length: 20000
  run_units: iteration
  precision: float32
  # epoch: 1000
output_dir: "output/"
