
defaults:
  - base_config
  - override framework: torch
  - _self_
  
data:
  downsample: 1 # Change to 0
  version: 2
  data_format: channels_first
  file: "cosmic_tagging_2_train.h5"
  aux_file: "cosmic_tagging_2_val.h5"

network:
  n_initial_filters: 64
  classification:
    active: False
    detach: True
  vertex:
    active: False
    detach: True
  blocks_deepest_layer: 3
  blocks_final: 3
  depth: 6 # changed from 5 to 6
  upsampling: convolutional
run:
  id: ds(0)_filters(32)_train_2023-02-28-fp32
  minibatch_size: 1
  iterations: 250
  precision: float32
  epoch: 1000
  distributed: False
  compute_mode: GPU
  # profile: True
output_dir: "//lus/grand/projects/datascience/cadams/CT-SN-RUNS"
